#!/usr/bin/python3  
from bcc import BPF

# Programs that will be compiled and loaded into the kernel
program = r"""
int helloworld(void *ctx) {
    bpf_trace_printk("Hello World!");
    
    return 0;
}
"""

# Compile the ebpf program and attach "helloworld" to "execve" syscalls
b = BPF(text=program)
syscall = b.get_syscall_fnname("execve")
b.attach_kprobe(event=syscall, fn_name="helloworld")

# Continuously print all traces being generated by ebpf programs
b.trace_print()